### ISSUE TITLE
IOError: The stream is not java serialized object. Invalid stream header: ACED0573

### ISSUE THREAD

**Issue by hktalent** [vbuell/python-javaobj#7]
```
import javaobj

with open("/Users/0x101/safe/mytools_10012106/pwnjvm/test/8848.bin", "rb") as fd:
	jobj = fd.read()
	pobj = javaobj.loads(jobj)
	print(pobj)


 python test.py
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    pobj = javaobj.loads(jobj)
  File "/usr/local/lib/python2.7/site-packages/javaobj.py", line 44, in loads
    marshaller = JavaObjectUnmarshaller(f)
  File "/usr/local/lib/python2.7/site-packages/javaobj.py", line 155, in __init__
    self._readStreamHeader()
  File "/usr/local/lib/python2.7/site-packages/javaobj.py", line 178, in _readStreamHeader
    raise IOError("The stream is not java serialized object. Invalid stream header: %04X%04X" % (magic, version))
IOError: The stream is not java serialized object. Invalid stream header: ACED0573

```

**Comment by hktalent** [comment]
```
$ python3 test.py
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import javaobj
  File "/usr/local/lib/python3.7/site-packages/javaobj.py", line 171
    except Exception, e:
                    ^
SyntaxError: invalid syntax
```

**Comment by hktalent** [comment]
```
google:test 0x101$ pip3 install git+https://github.com/vbuell/python-javaobj
Collecting git+https://github.com/vbuell/python-javaobj
  Cloning https://github.com/vbuell/python-javaobj to /private/var/folders/4w/zz2jbf_j037djzhc_zj74m2w0000gn/T/pip-req-build-9wgv7rbo
Building wheels for collected packages: javaobj
  Building wheel for javaobj (setup.py) ... done
  Stored in directory: /private/var/folders/4w/zz2jbf_j037djzhc_zj74m2w0000gn/T/pip-ephem-wheel-cache-a6hv8kn3/wheels/34/bf/46/10ae1987503d823d4e6009cb73a9ad69343fb557cf7ed748a7
Successfully built javaobj
Installing collected packages: javaobj
Successfully installed javaobj-0.1.0
google:test 0x101$ python3 test.py
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import javaobj
  File "/usr/local/lib/python3.7/site-packages/javaobj.py", line 24, in <module>
    import StringIO
ModuleNotFoundError: No module named 'StringIO'
google:test 0x101$ pip3 uninstall git+https://github.com/vbuell/python-javaobj
You must give at least one requirement to uninstall (see "pip help uninstall")
google:test 0x101$ pip install git+https://github.com/vbuell/python-javaobj
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting git+https://github.com/vbuell/python-javaobj
  Cloning https://github.com/vbuell/python-javaobj to /private/var/folders/4w/zz2jbf_j037djzhc_zj74m2w0000gn/T/pip-req-build-MuqqlW
Building wheels for collected packages: javaobj
  Building wheel for javaobj (setup.py) ... done
  Stored in directory: /private/var/folders/4w/zz2jbf_j037djzhc_zj74m2w0000gn/T/pip-ephem-wheel-cache-TZFDlE/wheels/34/bf/46/10ae1987503d823d4e6009cb73a9ad69343fb557cf7ed748a7
Successfully built javaobj
Installing collected packages: javaobj
Successfully installed javaobj-0.1.0
google:test 0x101$ python test.py
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    jobj = self.read_file("/Users/0x101/safe/mytools_10012106/pwnjvm/test/8848.bin")
NameError: name 'self' is not defined
google:test 0x101$ python test.py
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    pobj = javaobj.loads(jobj)
  File "/usr/local/lib/python2.7/site-packages/javaobj.py", line 72, in loads
    marshaller = JavaObjectUnmarshaller(f)
  File "/usr/local/lib/python2.7/site-packages/javaobj.py", line 255, in __init__
    self._readStreamHeader()
  File "/usr/local/lib/python2.7/site-packages/javaobj.py", line 285, in _readStreamHeader
    raise IOError("The stream is not java serialized object. Invalid stream header: %04X%04X" % (magic, version))
IOError: The stream is not java serialized object. Invalid stream header: ACED0573
```
